name: SpazeUtils
version: '${project.version}'
main: com.spazeutils.Main
api-version: 1.18
authors: [ Das_Randmeer, Theminestone ]
description: SpazeUtils
website: github.com/Theminestone/SpazeUtils

commands:
  wb:
    description: Opens the Workbench
  ec:
    description: Opens the Enderchest
  login:
    description: login [password]
  stats:
    description: Shows Server Informations
  ping:
    description: Showes a Players Ping
  pw:
    description: Password Utility
  rules:
    description: Server Rules
  invsee:
    description: See a Player's Inventory
  info:
    description: Show Player Information